# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25e8131e9fcc6aff17ec66895af4e2cf5e723a1a785f1cd93e23d74786afb46b9608a8a57a07a44f7e505f100cabdac48d973bcb687dc3fe1afdda6050672f34

test:
  secret_key_base: d25edf44d517fe497461f19ab6e4c7a5dd893010a09db809c1f2b2aef8a1b6114b8732117d878d2fec7194ed35ac33c978a99cf6c341f2bea4e5bc2f52c78173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
